#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         cpan2rpm
version:      2.018
version_from: cpan2rpm
installdirs:  site
requires:
    HTTP::Request:                 0
    LWP::UserAgent:                0
    ExtUtils::MakeMaker:           5.4302

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
